### ISSUE TITLE
Crear modelos estaticos

### ISSUE THREAD

**Issue by erickjosue8916** [Steve-Hndz/UFront-End#23]
# Definir estos modelos
> Solo agregar el método list, según la documentación en el issue de modelos (estos, modelos no tienen JOINS, omitir esa parte y no confundir / a excepción de Hospitales), estos seran solo de lectura

- Departamentos
- Municipios
- Hospitales

**Comment by CoreasMarlon** [comment]
Aqui estoy trabajando yo, váyanse alv

**Comment by erickjosue8916** [comment]
# Falta el modelo Sangre se me escapo

**Comment by CoreasMarlon** [comment]
Definido
