### ISSUE TITLE
Pacientes y donantes

### ISSUE THREAD

**Issue by erickjosue8916** [Steve-Hndz/UFront-End#25]
# Replicar donantes en pacientes, con su variante

- Definir los métodos planteados en el issue Modelos, colocando los cambios necesarios
- Crear función en ambos modelos que permita, la validación respecto a una contraseña con una contraseña encriptada, traída de la base de datos, segun el metodo de encriptado usado

```php
public funtion verifyPassword ($password) {
   $isValidPassword = false
   // your verification code here...
   return $isValidPassword
}
```

**Comment by jvrmrls** [comment]
TERMINADO! A falta de revision de sintaxis y funcionabilidad
