### ISSUE TITLE
Datos estaticos

### ISSUE THREAD

**Issue by erickjosue8916** [Steve-Hndz/UFront-End#26]
# Creación de información de prueba

- Agregar mas municipios (no todos, solo una cantidad razonable mínimo unos 4 por departamento a la base de datos)
- Agregar los tipos de sangre
- Agregar Hospitales
- Exportar la base de datos, a en un archivo sql, y colocarlo en la carpeta database

**Comment by EddyRC** [comment]
Trabajando en ello
