### ISSUE TITLE
Alojamiento de la base de datos

### ISSUE THREAD

**Issue by erickjosue8916** [Steve-Hndz/UFront-End#46]
# Revisar los sigueintes recursos

https://www.freemysqlhosting.net/
https://www.db4free.net/index.php?language=es

- Implementar una prueba
- Identificar limites y requerimientos

**Comment by jvrmrls** [comment]
Yo he usado eso y no me dejaba usar claves foráneas

**Comment by erickjosue8916** [comment]
Exporta el código, SQL y lo importas ahí, quiza vista grafica no tiene para eso

**Comment by jvrmrls** [comment]
URL: databases.000webhost.com         user: id14195150_sistemas2020       pass: id14195150_sistemas2020     db: id14195150_db_bloodproject

**Comment by jvrmrls** [comment]
https://www.000webhost.com/

Limites: No permite crear vistas - No permite crear relaciones con llaves foraneas - No permite crear procedimientos - No permite crear tablas desde codigo SQL - Solo permite crear tablas mediante importacion de SQL
