### ISSUE TITLE
Datatable

### ISSUE THREAD

**Issue by erickjosue8916** [Steve-Hndz/UFront-End#54]
# Configurar Data Table

- Llevar a cabo la configuración de data table, para poder filtrar, ordenar y paginar en base a este

**Comment by erickjosue8916** [comment]
Ya esta agregado en el archivo main.js, ahi se deben hacer las modificaciones

**Comment by EddyRC** [comment]
Configuracion del dataTable terminada, ya esta en funcionamiento
